### ISSUE TITLE
Minor error in docs

### ISSUE THREAD

**Issue by jpgringo** [kbrw/node_erlastic#8]
Docs indicate that `require('node_erlastic')` or `var Bert = require('node_erlastic/bert')` will work unaltered from the legacy repo. As it stands, require references must be to `@kbrw/node_erlastic` and `@kbrw/node_erlastic/bert`, respectively.

Using Node v14.15.1 and Yarn 1.22.10.

**Comment by Shakadak** [comment]
Hi, indeed, thanks for the reminder
